name: build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "30.1"
      - name: Build vsd
        run: cargo build -p vsd
      - name: Set up upload environment
        uses: benjlevesque/short-sha@v3.0
      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-${{ env.SHA }}-debug-x86_64-unknown-linux-gnu"
          path: target/debug/vsd
