name: Build on Test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
    runs-on: ubuntu-24.04
    steps:
      - name: Install Zig
        uses: jetsung/install-zig@v0.0.2
      - name: Show zig version
        run: |
          zig version
