name: Build on Test

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: x86_64
          - os: linux
            arch: aarch64
          - os: linux
            arch: loongarch64            
          - os: macos
            arch: x86_64
          - os: macos
            arch: aarch64
          - os: windows
            arch: x86_64
          - os: windows
            arch: aarch64
    runs-on: ubuntu-24.04
    steps:
      - name: Install Zig (specific version)
        uses: ./.github/actions/install-zig
        with:
          version: "0.14.1"
      - name: Show zig version
        run: |
          zig version
